services:
  Tailr\SuluTranslationsBundle\Domain\Command\ExportHandler:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Tailr\SuluTranslationsBundle\Domain\Action\ExportAction'
      - '@Tailr\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Tailr\SuluTranslationsBundle\Domain\Command\RemoveHandler:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Tailr\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Tailr\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Tailr\SuluTranslationsBundle\Domain\Command\UpdateHandler:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Tailr\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Tailr\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Tailr\SuluTranslationsBundle\Domain\Command\WriteHandler:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Tailr\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Tailr\SuluTranslationsBundle\Domain\Events\EventDispatcher'