services:
  tailr_translations.utc_clock:
    class: Symfony\Component\Clock\NativeClock
    arguments:
      - 'utc'

  Tailr\SuluTranslationsBundle\Infrastructure\Sulu\Admin\TranslationsAdmin:
    arguments:
      - '@sulu_admin.view_builder_factory'
      - '@sulu_security.security_checker'
    tags:
      - { name: 'sulu.admin' }
      - { name: 'sulu.context', context: 'admin' }