services:
  Tailr\SuluTranslationsBundle\Infrastructure\Sulu\Admin\TranslationsAdmin:
    arguments:
      - '@sulu_admin.view_builder_factory'
      - '@sulu_security.security_checker'
    tags:
      - { name: 'sulu.admin' }
      - { name: 'sulu.context', context: 'admin' }