services:
  tailr_translations.utc_clock:
    class: Symfony\Component\Clock\NativeClock
    arguments:
      - 'utc'
  Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Time\UtcClock:
    arguments:
      - '@tailr_translations.utc_clock'
  Tailr\SuluTranslationsBundle\Domain\Time\Clock: '@Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Time\UtcClock'
